services:
  web_biz:
    build: .
    image: php:7.4-apache
    container_name: php-container-biz
    volumes:
      - ./test:/var/www/html
    ports:
      - "80:80"  # Map live domain to container's Apache server
    environment:
      VIRTUAL_HOST: bizbill.4asolutions.com.au
    depends_on:
      - db_biz

  db_biz:
    image: mysql:5.7
    container_name: mysql-container-biz
    environment:
      MYSQL_ROOT_PASSWORD: Jaya@1975
      MYSQL_DATABASE: ngkproje_bizbill
      MYSQL_USER: ngkproje_ajay
      MYSQL_PASSWORD: Jaya@1975
    ports:
      - "3306:3306"  # Match cPanel's default MySQL port
    volumes:
      - db_data_biz:/var/lib/mysql

  frontend_biz:
    container_name: react-container-biz
    build: ./frontend_biz
    volumes:
      - ./frontend_biz:/frontend
      - /frontend/node_modules
    ports:
      - "3000:3000"  # React app on standard live port
    stdin_open: true
    tty: true
    environment:
      REACT_APP_API_URL: "https://bizbill.4asolutions.com.au"  # Updated API URL

volumes:
  db_data_biz:
